In [52]:
import pandas as pd

df_majors = pd.DataFrame(columns=[
    "marathon",
    "city",
    "country",
    "date",
    "year",
    
    # rendimiento
    "elite_time_winner_M",
    "elite_time_winner_F",
    "average_men_time",
    "average_women_time",
    
    # participación
    "participants",
    "finishers",
    "completion_rate",
    
    # clima
    "temperature_start_c",
    "humidity_in_%",
    "wind_speed_kmh",
    "weather_notes",
    
    # dificultad
    "elevation_gain_m",
    "course_type",
    
    # popularidad
    "applications",

    # trazabilidad
    "source",
    
    # extra
    "notes"
])

df_majors

Empty DataFrame
Columns: [marathon, city, country, date, year, elite_time_winner_M, elite_time_winner_F, average_men_time, average_women_time, participants, finishers, completion_rate, temperature_start_c, humidity_in_%, wind_speed_kmh, weather_notes, elevation_gain_m, course_type, applications, source, notes]
Index: []

[0 rows x 21 columns]

In [ ]:
#Datos Tokyo Marathon 2025 introducidos manualmente

df_majors.loc[len(df_majors)] = {
    "marathon": "Tokyo Marathon",
    "city": "Tokyo",
    "country": "Japan",
    "date": "2025-03-02",
    "year": 2025,

    "elite_time_winner_M": "02:03:23",
    "elite_time_winner_F": "02:16:31",
    "average_men_time": "04:41:00",
    "average_women_time": "05:04:00",

    "participants": 37791,
    "finishers": 36204,
    "completion_rate": 96.6,

    "temperature_start_c": 8.0,
    "humidity_in_%": 58,
    "wind_speed_kmh": 1.1,
    "weather_notes": "Cool and dry",

    "elevation_gain_m": 45,
    "course_type": "Flat urban loop",

    "applications": 300000,

    "source": "Official Tokyo Marathon website + official results page",
    "notes": "Participants estimated. Elevation estimated from course profile."
}

In [54]:
import numpy as np

# -----------------------
# DATOS TOKYO (MEN)
# -----------------------

men = np.array([
    1644,                         # <3h
    7684 - 1644,                  # 3–4h
    8028 - 7684,                  # 4–5h
    5927,                         # 5–6h
    3424                          # 6–7h
])

# -----------------------
# DATOS TOKYO (WOMEN)
# -----------------------

women = np.array([
    133,                          # <3h
    1658 - 133,                   # 3–4h
    3139 - 1658,                  # 4–5h
    2777,                         # 5–6h
    1723                          # 6–7h
])

# -----------------------
# TIEMPOS MEDIOS POR RANGO
# -----------------------

tiempos = np.array([2.5, 3.5, 4.5, 5.5, 6.5])  # horas

# -----------------------
# MEDIA PONDERADA
# -----------------------

average_men_time = np.sum(men * tiempos) / np.sum(men)
average_women_time = np.sum(women * tiempos) / np.sum(women)

print("Average men time (hours):", average_men_time)
print("Average women time (hours):", average_women_time)

Average men time (hours): 4.698342827550492
Average women time (hours): 5.08018065191779

In [55]:
def hours_to_hhmm(h):
    hours = int(h)
    minutes = int((h - hours) * 60)
    return f"{hours:02d}:{minutes:02d}"

print("Men:", hours_to_hhmm(average_men_time))
print("Women:", hours_to_hhmm(average_women_time))

Men: 04:41
Women: 05:04

In [ ]:
#Datos Chicago Marathon 2025 introducidos manualmente

df_majors.loc[len(df_majors)] = {
    "marathon": "Chicago Marathon",
    "city": "Chicago",
    "country": "USA",
    "date": "2025-10-12",
    "year": 2025,

    "elite_time_winner_M": "02:02:23",
    "elite_time_winner_F": "02:14:57",
    "average_men_time": "03:55:44",
    "average_women_time": "04:32:48",

    "participants": 55000,
    "finishers": 54383,
    "completion_rate": 98.8,

    "temperature_start_c": 10.0,
    "humidity_in_%": 85,
    "wind_speed_kmh": 4.8,
    "weather_notes": "Partially cloudy",

    "elevation_gain_m": 35,
    "course_type": "Flat and looped road course",

    "applications": 160000,

    "source": "Bank of America Chicago Marathon official website and Findmymarathon website",
    "notes": "Participants estimated. Elevation estimated from course profile."
}

In [ ]:
# Datos Berlin Marathon 2025 introducidos manualmente

df_majors.loc[len(df_majors)] = {
    "marathon": "Berlin Marathon",
    "city": "Berlin",
    "country": "Germany",
    "date": "2025-09-21",
    "year": 2025,

    "elite_time_winner_M": "02:02:16",
    "elite_time_winner_F": "02:21:08",
    "average_men_time": "04:37:19",
    "average_women_time": None,

    "participants": 55000,
    "finishers": 48020,
    "completion_rate": 87.3,

    "temperature_start_c": 19.0,
    "humidity_in_%": 68,
    "wind_speed_kmh": 14.4,
    "weather_notes": "Temperatura mas alta registrada",

    "elevation_gain_m": 25,
    "course_type": "Flat urban course",

    "applications": 170000,

    "source": "BMW Berlin Marathon website, Findmymarathon website",
    "notes": "Participants estimated. Elevation estimated from course profile. Average women time not available"
    }

In [ ]:
# Datos London Marathon 2025 introducidos manualmente

df_majors.loc[len(df_majors)] = {
    "marathon": "London Marathon",
    "city": "London",
    "country": "UK",
    "date": "2025-04-27",
    "year": 2025,

    "elite_time_winner_M": "02:02:27",
    "elite_time_winner_F": "02:15:50",
    "average_men_time": "04:23:00",
    "average_women_time": "05:01:00",

    "participants": 64053,
    "finishers": 56640,
    "completion_rate": 88.4,

    "temperature_start_c": 12.0,
    "humidity_in_%": 76,
    "wind_speed_kmh": 3.2,
    "weather_notes": "Despejado y soleado",

    "elevation_gain_m": 127,
    "course_type": "Flat urban course",

    "applications": 840318,

    "source": "TCS London Marathon website, Findmymarathon website",
    "notes": "Participants estimated. Elevation estimated from course profile."
    }

In [ ]:
# Datos New York Marathon 2025 introducidos manualmente

df_majors.loc[len(df_majors)] = {
    "marathon": "New York Marathon",
    "city": "New York",
    "country": "USA",
    "date": "2025-11-02",
    "year": 2025,

    "elite_time_winner_M": "02:08:09",
    "elite_time_winner_F": "02:19:51",
    "average_men_time": "04:18:55",
    "average_women_time": "04:48:11",

    "participants": 59662,
    "finishers": 59221,
    "completion_rate": 99.3,

    "temperature_start_c": 7.0,
    "humidity_in_%": 69,
    "wind_speed_kmh": None,
    "weather_notes": "No habia viento este dia",

    "elevation_gain_m": 246,
    "course_type": "Point to Point road racing course",

    "applications": 200000,

    "source": "TCS New York Marathon website, Findmymarathon website",
    "notes": "Participants estimated. Elevation estimated from course profile."
    }

In [ ]:
# Datos Boston Marathon 2025 introducidos manualmente

df_majors.loc[len(df_majors)] = {
    "marathon": "Boston Marathon",
    "city": "Boston",
    "country": "USA",
    "date": "2025-04-21",
    "year": 2025,

    "elite_time_winner_M": "02:04:45",
    "elite_time_winner_F": "02:17:22",
    "average_men_time": "03:33:31",
    "average_women_time": "03:56:02",

    "participants": 28845,
    "finishers": 28409,
    "completion_rate": 98.5,

    "temperature_start_c": 9,
    "humidity_in_%": 35,
    "wind_speed_kmh": 8,
    "weather_notes": "Partially clouded",

    "elevation_gain_m": 248,
    "course_type": "Point to Point road/pavement",

    "applications": 36393,

    "source": "Boston Athletic Association website, Findmymarathon website",
    "notes": "Participants estimated. Elevation estimated from course profile."
    }

In [ ]:
# Datos Sydney Marathon 2025 introducidos manualmente

df_majors.loc[len(df_majors)] = {
    "marathon": "Sydney Marathon",
    "city": "Sydney",
    "country": "Australia",
    "date": "2025-08-31",
    "year": 2025,

    "elite_time_winner_M": "02:06:06",
    "elite_time_winner_F": "02:18:22",
    "average_men_time": None,
    "average_women_time": None,

    "participants": 35000,
    "finishers": 32976,
    "completion_rate": 94.2,

    "temperature_start_c": 8,
    "humidity_in_%": 64,
    "wind_speed_kmh": 13,
    "weather_notes": "Clear",

    "elevation_gain_m": 317,
    "course_type": "Point to Point road/pavement",

    "applications": 79000,

    "source": "TCS SYdney Marathon website, Findmymarathon website",
    "notes": "Participants estimated. Elevation estimated from course profile. Average Men and Women time not available"
    }

In [64]:
df_majors.to_csv("../data/external/majors_2025_manual.csv", index=False)

In [66]:
df_majors.info()

<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 6
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   marathon             7 non-null      str
 1   city                 7 non-null      str
 2   country              7 non-null      str
 3   date                 7 non-null      str
 4   year                 7 non-null      int64
 5   elite_time_winner_M  7 non-null      str
 6   elite_time_winner_F  7 non-null      str
 7   average_men_time     6 non-null      object
 8   average_women_time   5 non-null      object
 9   participants         7 non-null      int64
 10  finishers            7 non-null      int64
 11  completion_rate      7 non-null      float64
 12  temperature_start_c  7 non-null      float64
 13  humidity_in_%        7 non-null      int64
 14  wind_speed_kmh       6 non-null      object
 15  weather_notes        7 non-null      str
 16  elevation_gain_m     7 non-null      int64
 17  course_type          7 non-null      str
 18  applications         7 non-null      int64
 19  source               7 non-null      str
 20  notes                7 non-null      str
dtypes: float64(2), int64(6), object(3), str(10)
memory usage: 1.2+ KB

In [67]:
df_majors.isnull().sum()

marathon               0
city                   0
country                0
date                   0
year                   0
elite_time_winner_M    0
elite_time_winner_F    0
average_men_time       1
average_women_time     2
participants           0
finishers              0
completion_rate        0
temperature_start_c    0
humidity_in_%          0
wind_speed_kmh         1
weather_notes          0
elevation_gain_m       0
course_type            0
applications           0
source                 0
notes                  0
dtype: int64

In [65]:
df_majors

,marathon,city,country,date,year,elite_time_winner_M,elite_time_winner_F,average_men_time,average_women_time,participants,...,completion_rate,temperature_start_c,humidity_in_%,wind_speed_kmh,weather_notes,elevation_gain_m,course_type,applications,source,notes
0,Tokyo Marathon,Tokyo,Japan,2025-03-02,2025,02:03:23,02:16:31,04:41:00,05:04:00,37791,...,96.6,8.0,58,1.1,Cool and dry,45,Flat urban loop,300000,Official Tokyo Marathon website + official res...,Datos introducidos manualmente. Tiempos averag...
1,Chicago Marathon,Chicago,USA,2025-10-12,2025,02:02:23,02:14:57,03:55:44,04:32:48,55000,...,98.8,10.0,85,4.8,Partially cloudy,35,Flat and looped road course,160000,Bank of America Chicago Marathon official webs...,Numero aproximado de participantes (no oficial...
2,Berlin Marathon,Berlin,Germany,21-09-2025,2025,02:02:16,02:21:08,04:37:19,None,55000,...,87.3,19.0,68,14.4,Temperatura mas alta registrada,25,Flat urban course,170000,"BMW Berlin Marathon website, Findmymarathon we...",Numero aproximado de participantes (no oficial...
3,London Marathon,London,UK,27-04-2025,2025,02:02:27,02:15:50,04:23:00,05:01:00,64053,...,88.4,12.0,76,3.2,Despejado y soleado,127,Flat urban course,840318,"TCS London Marathon website, Findmymarathon we...",Datos introducidos manualmente. Elevation gain...
4,New York Marathon,New York,USA,02-11-2025,2025,02:08:09,02:19:51,04:18:55,04:48:11,59662,...,99.3,7.0,69,None,No habia viento este dia,246,Point to Point road racing course,200000,"TCS New York Marathon website, Findmymarathon ...",Datos introducidos manualmente. Elevation gain...
5,Boston Marathon,Boston,USA,21-04-2025,2025,02:04:45,02:17:22,03:33:31,03:56:02,28845,...,98.5,9.0,35,8,Partially clouded,248,Point to Point road/pavement,36393,"Boston Athletic Association website, Findmymar...",Datos introducidos manualmente. Elevation gain...
6,Sydney Marathon,Sydney,Australia,31-08-2025,2025,02:06:06,02:18:22,None,None,35000,...,94.2,8.0,64,13,Clear,317,Point to Point road/pavement,79000,"TCS SYdney Marathon website, Findmymarathon we...",Datos introducidos manualmente. Elevation gain...